name: Publish GitHub Page
description: Publish a GitHub Page Action
author: Rizart Dokollari <r.dokollari@gmail.com>

branding:
  icon: layers
  color: gray-dark

inputs:
  directory:
    description: The directory to publish.
    required: true
  github-token:
    description: The token GitHub autogenerates
    required: true
  github-repository:
    description: The owner & repository. E.g. octocat/Hello-World
    required: true
  github-actor:
    description: The name of the person or app that initiated the workflow. For example, octocat.
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.github-actor }}
    - ${{ inputs.github-token }}
    - ${{ inputs.github-repository }}
