name: Build
on:
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build page
        run: |
          mkdir build
          DATE=$(date)
          echo "Published at $DATE" >> build/index.html
          echo "<a href='https://github.com/rdok/publish-gh-page-action/commit/${GITHUB_SHA}'>${GITHUB_SHA}</a>" >> build/index.html
      - name: Trigger publish action
        uses: ./
        with:
          directory: build
          github-actor: ${{ github.actor }}
          github-token: ${{ github.token }}
          github-repository: ${{ github.repository }}
      - name: Waiting for GitHub to publish the page
        run: sleep 30
      - name: Test contents of published page
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY}" | sed --expression 's/\/.*//g')
          REPO=$(echo "${GITHUB_REPOSITORY}" | sed --expression 's/.*\///g')
          response=$(curl https://"${OWNER}".github.io/${REPO}/)
          if [[ "$response" != *"$GITHUB_SHA"* ]]; then
            echo "Unable to find ${GITHUB_SHA} in the published page."
            echo "Actual content: $response"
            exit 1
          fi
